name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install LLVM and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-dev clang lld
        sudo apt-get install -y libmlir-dev
        sudo apt-get install -y nvidia-cuda-toolkit
    
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        cmake --build .
    
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
